---
# https://github.com/troessner/reek#configuration-file
detectors:
  IrresponsibleModule:
    enabled: false
  FeatureEnvy:
    enabled: true
  UtilityFunction:
    enabled: true
    exclude:
      - EmailSyncJob#process_and_broadcast_result
  MissingSafeMethod:
    enabled: true
    exclude:
      - GmailAdapter
  NilCheck:
    enabled: false
  TooManyStatements:
    enabled: true
    exclude:
      - initialize
      - User#self.from_omniauth
      - EmailProcessingService#process_and_save_emails
    max_statements: 9
  UncommunicativeParameterName:
    enabled: true
    reject:
      - /^.$/
      - "/[0-9]$/"
      - "/[A-Z]/"
      - /^_/
  UncommunicativeVariableName:
    exclude:
      - EmailsController
    accept:
      - /^_$/
      - e
    enabled: true
    reject:
      - /^.$/
      - "/[0-9]$/"
      - "/[A-Z]/"
  DuplicateMethodCall:
    enabled: true
    exclude:
      - SessionsController#refresh_token
      - EmailRetrievalService#build_query
  UnusedParameters:
    enabled: true
    exclude:
      - Email#self.ransackable_associations
      - Email#self.ransackable_attributes
  InstanceVariableAssumption:
    enabled: true
    exclude:
      - EmailsController
  LongParameterList:
    enabled: true
    exclude:
      - GmailAdapter#list_user_messages
  

exclude_paths:
  - vendor/bundle
  - db/migrate
  - app/controllers/users/omniauth_callbacks_controller.rb
