require: rubocop-rspec

RSpec/ExampleLength:
  Enabled: true
  Max: 10
  CountAsOne:
    - array
    - hash
    - heredoc

RSpec/ExampleWithoutDescription:
  Enabled: true
  EnforcedStyle: single_line_only
RSpec/SubjectStub:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 10
